let orgElements = [
	{
		id: 1,
		name: "Assata’s Daughters",
		description: "Assata’s Daughters (“AD”) is a Black woman-led, young person-directed organization rooted in the Black Radical Tradition. AD organizes young Black people in Chicago by providing them with political education, leadership development, mentorship, and revolutionary services.",
		infoButtonText: "Info",
		infoButtonLink: "https://www.assatasdaughters.org/",
		donateButtonText: "Donate",
		donateButtonLink: "https://www.assatasdaughters.org/donate-1",
	},
	{
		id: 2,
		name: "BLM Chicago",
		description: "BLM CHI is one of *many* iterations of #BlackLivesMatter: a movement, a rebellion, an affirmation, an intervention… and so much more.",
		infoButtonText: "Info",
		infoButtonLink: "https://www.facebook.com/BLMChi/",
		donateButtonText: "Donate",
		donateButtonLink: "https://www.paypal.com/paypalme/BLMCHI",
	},
	{
		id: 3,
		name: "Brave Space Alliance",
		description: "Brave Space Alliance is the first Black-led, trans-led LGBTQ+ Center located on the South Side of Chicago, dedicated to creating and providing affirming, culturally competent, for-us by-us resources, programming, and services for LGBTQ+ individuals on the South and West sides of the city.",
		infoButtonText: "Info",
		infoButtonLink: "https://www.bravespacealliance.org/",
		donateButtonText: "Donate",
		donateButtonLink: "https://www.bravespacealliance.org/donate",
		donateButtonTextB: "Trans Relief Fund",
		donateButtonLinkB: "https://actionnetwork.org/fundraising/trans-relief-fund",
	},
	{
		id: 4,
		name: "BYP100",
		description: "BYP100 (Black Youth Project 100) is a member-based organization of Black youth activists creating justice and freedom for all Black people.",
		infoButtonText: "Info",
		infoButtonLink: "https://www.byp100ef.org/",
		donateButtonText: "Donate",
		donateButtonLink: "https://secure.actblue.com/donate/byp100-ef-1",
	},
	{
		id: 5,
		name: "Chicago Alliance Against Racist and Political Repression",
		description: "Since 1973, when it was born from the movement to free Angela Davis and all political prisoners, the Chicago Alliance Against Racist and Political Repression has defended the rights of oppressed people in Illinois and around the world.",
		infoButtonText: "Info",
		infoButtonLink: "https://www.caarpr.org/",
		donateButtonText: "Donate",
		donateButtonLink: "https://www.caarpr.org/fundraising",
	},
	{
		id: 6,
		name: "Chicago Community Bond Fund",
		description: "The Chicago Community Bond Fund (CCBF) pays bond for people charged with crimes in Cook County, Illinois. Through a revolving fund, CCBF supports individuals whose communities cannot afford to pay the bonds themselves and who have been impacted by structural violence.",
		infoButtonText: "Info",
		infoButtonLink: "https://chicagobond.org/",
		donateButtonText: "Donate",
		donateButtonLink: "https://chicagobond.org/donate/",
	},
	{
		id: 7,
		name: "Chicago Freedom School",
		description: "Founded in 2007, CFS creates new generations of critical thinkers who use their unique experiences and power to create a just world. Inspired by the Mississippi Freedom Schools of the Civil Rights Era, CFS takes an innovative approach to youth activism, leadership development, and movement building.",
		infoButtonText: "Info",
		infoButtonLink: "https://chicagofreedomschool.org/",
		donateButtonText: "Donate",
		donateButtonLink: "https://chicagofreedomschool.org/support-us/donate/",
	},
	{
		id: 8,
		name: "EAT (Equity & Transformation)",
		description: "Founded and established for and by post incarcerated and marginalized Black people in Chicago, Equity And Transformation strives to uplift the faces, voices, and power of the vast disenfranchised and excluded Black workforce in Chicago. \"We organize with individuals that operate outside of the formal economy.\"",
		infoButtonText: "Info",
		infoButtonLink: "https://www.eatchicago.org/",
		donateButtonText: "Donate",
		donateButtonLink: "https://donorbox.org/donate-now-266",
	},
	{
		id: 9,
		name: "Good Kids Mad City",
		description: "Good Kids Mad City - Englewood is focused on developing young leaders to advocate for resources that will allow them to create sustainable, livable community conditions as well as provide tools to address both mental and physical trauma.",
		infoButtonText: "Info",
		infoButtonLink: "https://www.gkmcenglewood.com/",
		donateButtonText: "Donate",
		donateButtonLink: "https://secure.actblue.com/donate/gkmc-1",
	},
	{
		id: 10,
		name: "Let Us Breathe Collective",
		description: "The #LetUsBreathe Collective is an alliance of artists and activists organizing through a creative lens to imagine a world without prisons and police.",
		infoButtonText: "Info",
		infoButtonLink: "https://www.letusbreathecollective.com/",
		donateButtonText: "Donate",
		donateButtonLink: "https://www.letusbreathecollective.com/support",
	},
	{
		id: 11,
		name: "Love + Protect",
		description: "Love & Protect supports those who identify as women and gender non-conforming persons of color who are criminalized or harmed by state and interpersonal violence. Through love, they work towards healing and transformation with these individuals and their families.",
		infoButtonText: "Info",
		infoButtonLink: "https://loveprotect.org/",
		donateButtonText: "Donate",
		donateButtonLink: "https://donorbox.org/embed/love-protect",
	},
];
  
export default orgElements;